export const baseProfiles = [
  {
    id: "ja",
    label: "Japanese · Japan",
    place: "Kyoto, Japan",
    language: "Japanese",
    order: "family-given",
    given: ["Akari", "Haruka", "Yui", "Aoi", "Ren", "Sota", "Haruto", "Kaito"],
    family: [
      "Ueno",
      "Sato",
      "Tanaka",
      "Mori",
      "Fujita",
      "Nakamura",
      "Ishikawa",
      "Okada",
    ],
    note: "Family name first in Japanese contexts. Romanized forms; spellings and personal preferences vary.",
  },
  {
    id: "ko",
    label: "Korean · South Korea",
    place: "Busan, South Korea",
    language: "Korean",
    order: "family-given",
    given: [
      "Ji-won",
      "Seo-yeon",
      "Min-jun",
      "Ji-ho",
      "Su-bin",
      "Ha-yoon",
      "Hyun-woo",
      "Seo-jun",
    ],
    family: ["Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Yoon", "Han"],
    note: "Family name first. Romanization and hyphenation vary by person; keep a character’s chosen spelling consistent.",
  },
  {
    id: "mx",
    label: "Mexican Spanish · Mexico",
    place: "Oaxaca, Mexico",
    language: "Spanish",
    order: "given-family",
    given: [
      "Lucía",
      "Mateo",
      "Valeria",
      "Diego",
      "Camila",
      "Emiliano",
      "Sofía",
      "Adrián",
    ],
    family: [
      "Hernández",
      "García",
      "López",
      "Martínez",
      "Ramírez",
      "Torres",
      "Mendoza",
      "Vargas",
    ],
    note: "This starter profile uses two family names. Many naming practices coexist in Mexico; edit order and preferred display as needed.",
  },
  {
    id: "fr",
    label: "French · France",
    place: "Lyon, France",
    language: "French",
    order: "given-family",
    given: [
      "Camille",
      "Julien",
      "Manon",
      "Émile",
      "Chloé",
      "Gabriel",
      "Léa",
      "Hugo",
    ],
    family: [
      "Moreau",
      "Laurent",
      "Bernard",
      "Dubois",
      "Petit",
      "Roux",
      "Garnier",
      "Lefebvre",
    ],
    note: "Contemporary French-language starter names. Location does not prescribe ancestry, nationality, or identity.",
  },
  {
    id: "en",
    label: "English-language · UK",
    place: "Bristol, United Kingdom",
    language: "English",
    order: "given-family",
    given: [
      "Eleanor",
      "Owen",
      "Amelia",
      "Theo",
      "Isabel",
      "Arthur",
      "Hazel",
      "Elliot",
    ],
    family: [
      "Bennett",
      "Clarke",
      "Reed",
      "Hughes",
      "Morgan",
      "Ellis",
      "Turner",
      "Brooks",
    ],
    note: "A small contemporary English-language pool, not a representation of all British communities.",
  },
  {
    id: "yo",
    label: "Yorùbá · Nigeria",
    place: "Ibadan, Nigeria",
    language: "Yorùbá",
    order: "given-family",
    given: [
      "Adéọlá",
      "Ayọ̀",
      "Dámilọ́lá",
      "Témítọ́pẹ́",
      "Bọ́lájí",
      "Olúwásẹ́un",
      "Fọlákẹ́",
      "Adébáyọ̀",
    ],
    family: ["Adéyẹmí", "Adélékè", "Ọládélé", "Adégòkè", "Ọlátúnjí", "Adéwálé"],
    note: "Starter Yorùbá names with diacritics; name boundaries and orthography require author review. Nigeria is culturally and linguistically diverse.",
  },
  {
    id: "custom",
    label: "Custom / invented culture",
    place: "Your world",
    language: "Author-defined",
    order: "given-family",
    given: ["Aven", "Ilyra", "Taren", "Sella", "Oren", "Veyra", "Cael", "Mira"],
    family: ["Voss", "Arden", "Tal", "Senn", "Maren", "Val"],
    note: "Fictional placeholder naming palette, not a claim of real-world cultural authenticity. Replace with your culture’s naming rules.",
  },
] as const;
