// Generated by scripts/create-places.py; curated starter geography.
export const placeData = [
  {
    id: "AR",
    name: "Argentina",
    aliases: [],
    profiles: ["ar-es"],
    regions: [
      {
        name: "Buenos Aires City",
        cities: ["Buenos Aires"],
      },
      {
        name: "Buenos Aires Province",
        cities: ["La Plata", "Mar del Plata"],
      },
      {
        name: "Córdoba",
        cities: ["Córdoba"],
      },
      {
        name: "Santa Fe",
        cities: ["Rosario", "Santa Fe"],
      },
      {
        name: "Mendoza",
        cities: ["Mendoza"],
      },
      {
        name: "Tucumán",
        cities: ["San Miguel de Tucumán"],
      },
    ],
    continents: ["South America"],
  },
  {
    id: "AU",
    name: "Australia",
    aliases: [],
    profiles: ["au-en"],
    regions: [
      {
        name: "New South Wales",
        cities: ["Sydney", "Newcastle"],
      },
      {
        name: "Victoria",
        cities: ["Melbourne", "Geelong"],
      },
      {
        name: "Queensland",
        cities: ["Brisbane", "Cairns"],
      },
      {
        name: "Western Australia",
        cities: ["Perth", "Fremantle"],
      },
      {
        name: "South Australia",
        cities: ["Adelaide"],
      },
      {
        name: "Tasmania",
        cities: ["Hobart", "Launceston"],
      },
      {
        name: "Australian Capital Territory",
        cities: ["Canberra"],
      },
      {
        name: "Northern Territory",
        cities: ["Darwin", "Alice Springs"],
      },
    ],
    continents: ["Oceania"],
  },
  {
    id: "BD",
    name: "Bangladesh",
    aliases: [],
    profiles: ["bd-bn"],
    regions: [
      {
        name: "Dhaka",
        cities: ["Dhaka"],
      },
      {
        name: "Chattogram",
        cities: ["Chattogram", "Cox’s Bazar"],
      },
      {
        name: "Khulna",
        cities: ["Khulna"],
      },
      {
        name: "Rajshahi",
        cities: ["Rajshahi"],
      },
      {
        name: "Sylhet",
        cities: ["Sylhet"],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "BR",
    name: "Brazil",
    aliases: ["Brasil"],
    profiles: ["br"],
    regions: [
      {
        name: "São Paulo",
        cities: ["São Paulo", "Campinas", "Santos"],
      },
      {
        name: "Rio de Janeiro",
        cities: ["Rio de Janeiro", "Niterói"],
      },
      {
        name: "Minas Gerais",
        cities: ["Belo Horizonte", "Uberlândia"],
      },
      {
        name: "Bahia",
        cities: ["Salvador", "Feira de Santana"],
      },
      {
        name: "Pernambuco",
        cities: ["Recife", "Olinda"],
      },
      {
        name: "Ceará",
        cities: ["Fortaleza", "Juazeiro do Norte"],
      },
      {
        name: "Paraná",
        cities: ["Curitiba", "Londrina"],
      },
      {
        name: "Rio Grande do Sul",
        cities: ["Porto Alegre", "Caxias do Sul"],
      },
      {
        name: "Santa Catarina",
        cities: ["Florianópolis", "Joinville"],
      },
      {
        name: "Amazonas",
        cities: ["Manaus", "Parintins"],
      },
      {
        name: "Pará",
        cities: ["Belém", "Santarém"],
      },
      {
        name: "Federal District",
        cities: ["Brasília"],
      },
      {
        name: "Goiás",
        cities: ["Goiânia", "Anápolis"],
      },
    ],
    continents: ["South America"],
  },
  {
    id: "CA",
    name: "Canada",
    aliases: [],
    profiles: ["ca-en", "ca-fr"],
    regions: [
      {
        name: "Alberta",
        cities: ["Calgary", "Edmonton"],
        profiles: ["ca-en"],
      },
      {
        name: "British Columbia",
        cities: ["Vancouver", "Victoria"],
        profiles: ["ca-en"],
      },
      {
        name: "Manitoba",
        cities: ["Winnipeg", "Brandon"],
        profiles: ["ca-en"],
      },
      {
        name: "New Brunswick",
        cities: ["Moncton", "Fredericton"],
        profiles: ["ca-en", "ca-fr"],
      },
      {
        name: "Newfoundland and Labrador",
        cities: ["St. John’s", "Corner Brook"],
        profiles: ["ca-en"],
      },
      {
        name: "Northwest Territories",
        cities: ["Yellowknife"],
        profiles: [],
      },
      {
        name: "Nova Scotia",
        cities: ["Halifax", "Sydney"],
        profiles: ["ca-en"],
      },
      {
        name: "Nunavut",
        cities: ["Iqaluit"],
        profiles: [],
      },
      {
        name: "Ontario",
        cities: ["Toronto", "Ottawa", "London"],
        profiles: ["ca-en", "ca-fr"],
      },
      {
        name: "Prince Edward Island",
        cities: ["Charlottetown"],
        profiles: ["ca-en"],
      },
      {
        name: "Québec",
        cities: ["Montréal", "Québec City", "Sherbrooke"],
        profiles: ["ca-fr", "ca-en"],
      },
      {
        name: "Saskatchewan",
        cities: ["Saskatoon", "Regina"],
        profiles: ["ca-en"],
      },
      {
        name: "Yukon",
        cities: ["Whitehorse"],
        profiles: [],
      },
    ],
    continents: ["North America"],
  },
  {
    id: "CL",
    name: "Chile",
    aliases: [],
    profiles: ["cl-es"],
    regions: [
      {
        name: "Santiago Metropolitan Region",
        cities: ["Santiago", "Puente Alto"],
      },
      {
        name: "Valparaíso",
        cities: ["Valparaíso", "Viña del Mar"],
      },
      {
        name: "Biobío",
        cities: ["Concepción", "Talcahuano"],
      },
      {
        name: "Antofagasta",
        cities: ["Antofagasta", "Calama"],
      },
      {
        name: "Los Lagos",
        cities: ["Puerto Montt", "Osorno"],
      },
    ],
    continents: ["South America"],
  },
  {
    id: "CN",
    name: "China",
    aliases: ["PRC", "中国"],
    profiles: ["cn-mandarin", "cn-cantonese"],
    regions: [
      {
        name: "Beijing",
        cities: ["Beijing"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Shanghai",
        cities: ["Shanghai"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Guangdong",
        cities: ["Guangzhou", "Shenzhen", "Foshan", "Dongguan", "Zhuhai"],
        profiles: ["cn-cantonese", "cn-mandarin"],
      },
      {
        name: "Sichuan",
        cities: ["Chengdu", "Mianyang", "Leshan", "Deyang"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Zhejiang",
        cities: ["Hangzhou", "Ningbo", "Wenzhou", "Jiaxing"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Jiangsu",
        cities: ["Nanjing", "Suzhou", "Wuxi", "Changzhou"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Hubei",
        cities: ["Wuhan", "Yichang", "Xiangyang"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Hunan",
        cities: ["Changsha", "Zhuzhou", "Hengyang"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Shandong",
        cities: ["Jinan", "Qingdao", "Yantai", "Weifang"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Henan",
        cities: ["Zhengzhou", "Luoyang"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Shaanxi",
        cities: ["Xi’an"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Fujian",
        cities: ["Fuzhou", "Xiamen", "Quanzhou", "Zhangzhou"],
        profiles: [],
      },
      {
        name: "Yunnan",
        cities: ["Kunming", "Dali"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Heilongjiang",
        cities: ["Harbin"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Liaoning",
        cities: ["Shenyang", "Dalian"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Chongqing",
        cities: ["Chongqing"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Hong Kong",
        cities: ["Hong Kong"],
        profiles: ["cn-cantonese", "cn-mandarin"],
      },
      {
        name: "Xinjiang",
        cities: ["Ürümqi", "Kashgar"],
        profiles: [],
      },
      {
        name: "Inner Mongolia",
        cities: ["Hohhot", "Baotou"],
        profiles: [],
      },
      {
        name: "Tibet",
        cities: ["Lhasa"],
        profiles: [],
      },
      {
        name: "Hebei",
        cities: [
          "Shijiazhuang",
          "Tangshan",
          "Baoding",
          "Qinhuangdao",
          "Chengde",
        ],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Shanxi",
        cities: ["Taiyuan", "Datong"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Anhui",
        cities: ["Hefei", "Wuhu"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Jiangxi",
        cities: ["Nanchang", "Jiujiang"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Guizhou",
        cities: ["Guiyang", "Zunyi"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Hainan",
        cities: ["Haikou", "Sanya"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Gansu",
        cities: ["Lanzhou", "Tianshui"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Qinghai",
        cities: ["Xining", "Golmud"],
        profiles: [],
      },
      {
        name: "Jilin",
        cities: ["Changchun", "Jilin City"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Tianjin",
        cities: ["Tianjin"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Guangxi",
        cities: ["Nanning", "Guilin"],
        profiles: ["cn-mandarin", "cn-cantonese"],
      },
      {
        name: "Ningxia",
        cities: ["Yinchuan", "Shizuishan"],
        profiles: ["cn-mandarin"],
      },
      {
        name: "Macao",
        cities: ["Macao"],
        profiles: ["cn-cantonese", "cn-mandarin"],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "CO",
    name: "Colombia",
    aliases: [],
    profiles: ["co-es"],
    regions: [
      {
        name: "Bogotá Capital District",
        cities: ["Bogotá"],
      },
      {
        name: "Antioquia",
        cities: ["Medellín"],
      },
      {
        name: "Valle del Cauca",
        cities: ["Cali"],
      },
      {
        name: "Atlántico",
        cities: ["Barranquilla"],
      },
      {
        name: "Bolívar",
        cities: ["Cartagena"],
      },
    ],
    continents: ["South America"],
  },
  {
    id: "EG",
    name: "Egypt",
    aliases: [],
    profiles: ["eg-ar"],
    regions: [
      {
        name: "Cairo",
        cities: ["Cairo"],
      },
      {
        name: "Alexandria",
        cities: ["Alexandria"],
      },
      {
        name: "Giza",
        cities: ["Giza"],
      },
      {
        name: "Luxor",
        cities: ["Luxor"],
      },
      {
        name: "Aswan",
        cities: ["Aswan"],
      },
    ],
    continents: ["Africa", "Asia"],
  },
  {
    id: "ET",
    name: "Ethiopia",
    aliases: [],
    profiles: ["et-am"],
    regions: [
      {
        name: "Addis Ababa",
        cities: ["Addis Ababa"],
        profiles: ["et-am"],
      },
      {
        name: "Amhara",
        cities: ["Bahir Dar", "Gondar"],
        profiles: ["et-am"],
      },
      {
        name: "Oromia",
        cities: ["Adama", "Jimma"],
        profiles: [],
      },
      {
        name: "Tigray",
        cities: ["Mekelle"],
        profiles: [],
      },
      {
        name: "Dire Dawa",
        cities: ["Dire Dawa"],
        profiles: [],
      },
    ],
    continents: ["Africa"],
  },
  {
    id: "FJ",
    name: "Fiji",
    aliases: [],
    profiles: ["fj-it"],
    regions: [
      {
        name: "Central Division",
        cities: ["Suva", "Nausori"],
      },
      {
        name: "Western Division",
        cities: ["Nadi", "Lautoka", "Ba"],
      },
      {
        name: "Northern Division",
        cities: ["Labasa", "Savusavu"],
      },
      {
        name: "Eastern Division",
        cities: ["Levuka"],
      },
    ],
    continents: ["Oceania"],
  },
  {
    id: "FR",
    name: "France",
    aliases: [],
    profiles: ["fr"],
    regions: [
      {
        name: "Île-de-France",
        cities: ["Paris", "Versailles"],
      },
      {
        name: "Auvergne-Rhône-Alpes",
        cities: ["Lyon", "Grenoble"],
      },
      {
        name: "Provence-Alpes-Côte d’Azur",
        cities: ["Marseille", "Nice"],
      },
      {
        name: "Occitanie",
        cities: ["Toulouse", "Montpellier"],
      },
      {
        name: "Nouvelle-Aquitaine",
        cities: ["Bordeaux"],
      },
      {
        name: "Brittany",
        cities: ["Rennes", "Brest"],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "DE",
    name: "Germany",
    aliases: ["Deutschland"],
    profiles: ["de"],
    regions: [
      {
        name: "Berlin",
        cities: ["Berlin"],
      },
      {
        name: "Bavaria",
        cities: ["Munich", "Nuremberg"],
      },
      {
        name: "Hamburg",
        cities: ["Hamburg"],
      },
      {
        name: "Hesse",
        cities: ["Frankfurt", "Wiesbaden"],
      },
      {
        name: "North Rhine-Westphalia",
        cities: ["Cologne", "Düsseldorf"],
      },
      {
        name: "Saxony",
        cities: ["Dresden", "Leipzig"],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "GH",
    name: "Ghana",
    aliases: [],
    profiles: ["gh-ak"],
    regions: [
      {
        name: "Ashanti",
        cities: ["Kumasi", "Obuasi"],
      },
      {
        name: "Eastern Region",
        cities: ["Koforidua", "Nsawam"],
      },
      {
        name: "Greater Accra",
        cities: ["Accra", "Tema"],
      },
      {
        name: "Central Region",
        cities: ["Cape Coast", "Winneba"],
      },
      {
        name: "Northern Region",
        cities: ["Tamale"],
        profiles: [],
      },
    ],
    continents: ["Africa"],
  },
  {
    id: "IN",
    name: "India",
    aliases: ["Bharat", "भारत"],
    profiles: [
      "in-hi",
      "in-mr",
      "in-ta",
      "in-te",
      "in-bn",
      "in-gu",
      "in-pa",
      "in-kn",
      "in-ml",
      "in-ur",
    ],
    regions: [
      {
        name: "Delhi",
        cities: ["New Delhi", "Delhi"],
        profiles: ["in-hi"],
      },
      {
        name: "Maharashtra",
        cities: ["Mumbai", "Pune", "Nagpur"],
        profiles: ["in-mr", "in-hi"],
      },
      {
        name: "Tamil Nadu",
        cities: ["Chennai", "Coimbatore", "Madurai"],
        profiles: ["in-ta"],
      },
      {
        name: "Telangana",
        cities: ["Hyderabad", "Warangal"],
        profiles: ["in-te", "in-ur"],
      },
      {
        name: "Andhra Pradesh",
        cities: ["Visakhapatnam", "Vijayawada"],
        profiles: ["in-te"],
      },
      {
        name: "Karnataka",
        cities: ["Bengaluru", "Mysuru", "Mangaluru"],
        profiles: ["in-kn"],
      },
      {
        name: "Kerala",
        cities: ["Kochi", "Thiruvananthapuram", "Kozhikode"],
        profiles: ["in-ml"],
      },
      {
        name: "West Bengal",
        cities: ["Kolkata", "Siliguri"],
        profiles: ["in-bn"],
      },
      {
        name: "Gujarat",
        cities: ["Ahmedabad", "Surat", "Vadodara"],
        profiles: ["in-gu"],
      },
      {
        name: "Punjab",
        cities: ["Ludhiana", "Amritsar"],
        profiles: ["in-pa"],
      },
      {
        name: "Chandigarh",
        cities: ["Chandigarh"],
        profiles: ["in-hi", "in-pa"],
      },
      {
        name: "Uttar Pradesh",
        cities: ["Lucknow", "Varanasi", "Kanpur"],
        profiles: ["in-hi"],
      },
      {
        name: "Rajasthan",
        cities: ["Jaipur", "Jodhpur"],
        profiles: ["in-hi"],
      },
      {
        name: "Madhya Pradesh",
        cities: ["Bhopal", "Indore"],
        profiles: ["in-hi"],
      },
      {
        name: "Bihar",
        cities: ["Patna", "Gaya"],
        profiles: ["in-hi"],
      },
      {
        name: "Haryana",
        cities: ["Gurugram", "Faridabad"],
        profiles: ["in-hi", "in-pa"],
      },
      {
        name: "Uttarakhand",
        cities: ["Dehradun", "Haridwar"],
        profiles: ["in-hi"],
      },
      {
        name: "Goa",
        cities: ["Panaji", "Margao"],
        profiles: [],
      },
      {
        name: "Assam",
        cities: ["Guwahati", "Dibrugarh"],
        profiles: [],
      },
      {
        name: "Odisha",
        cities: ["Bhubaneswar", "Cuttack"],
        profiles: [],
      },
      {
        name: "Jharkhand",
        cities: ["Ranchi", "Jamshedpur"],
        profiles: ["in-hi"],
      },
      {
        name: "Himachal Pradesh",
        cities: ["Shimla", "Dharamshala"],
        profiles: ["in-hi"],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "ID",
    name: "Indonesia",
    aliases: [],
    profiles: ["id-java", "id-sunda", "id-batak"],
    regions: [
      {
        name: "Jakarta",
        cities: ["Jakarta"],
        profiles: ["id-java", "id-sunda"],
      },
      {
        name: "West Java",
        cities: ["Bandung", "Bogor"],
        profiles: ["id-sunda"],
      },
      {
        name: "Central Java",
        cities: ["Semarang", "Surakarta"],
        profiles: ["id-java"],
      },
      {
        name: "East Java",
        cities: ["Surabaya", "Malang"],
        profiles: ["id-java"],
      },
      {
        name: "Special Region of Yogyakarta",
        cities: ["Yogyakarta"],
        profiles: ["id-java"],
      },
      {
        name: "North Sumatra",
        cities: ["Medan", "Pematangsiantar"],
        profiles: ["id-batak"],
      },
      {
        name: "Bali",
        cities: ["Denpasar", "Ubud"],
        profiles: [],
      },
      {
        name: "South Sulawesi",
        cities: ["Makassar"],
        profiles: [],
      },
      {
        name: "West Sumatra",
        cities: ["Padang"],
        profiles: [],
      },
      {
        name: "East Kalimantan",
        cities: ["Samarinda", "Balikpapan"],
        profiles: [],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "IR",
    name: "Iran",
    aliases: [],
    profiles: ["ir-fa"],
    regions: [
      {
        name: "Tehran",
        cities: ["Tehran"],
      },
      {
        name: "Fars",
        cities: ["Shiraz"],
      },
      {
        name: "Isfahan",
        cities: ["Isfahan"],
      },
      {
        name: "Razavi Khorasan",
        cities: ["Mashhad"],
      },
      {
        name: "East Azerbaijan",
        cities: ["Tabriz"],
        profiles: [],
      },
      {
        name: "Khuzestan",
        cities: ["Ahvaz"],
        profiles: [],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "IE",
    name: "Ireland",
    aliases: [],
    profiles: ["ie"],
    regions: [
      {
        name: "County Dublin",
        cities: ["Dublin"],
      },
      {
        name: "County Cork",
        cities: ["Cork", "Cobh"],
      },
      {
        name: "County Galway",
        cities: ["Galway"],
      },
      {
        name: "County Limerick",
        cities: ["Limerick"],
      },
      {
        name: "County Kerry",
        cities: ["Tralee", "Killarney"],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "IT",
    name: "Italy",
    aliases: ["Italia"],
    profiles: ["it"],
    regions: [
      {
        name: "Lazio",
        cities: ["Rome"],
      },
      {
        name: "Lombardy",
        cities: ["Milan", "Bergamo"],
      },
      {
        name: "Campania",
        cities: ["Naples"],
      },
      {
        name: "Tuscany",
        cities: ["Florence", "Pisa"],
      },
      {
        name: "Emilia-Romagna",
        cities: ["Bologna", "Parma"],
      },
      {
        name: "Sicily",
        cities: ["Palermo", "Catania"],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "JP",
    name: "Japan",
    aliases: [],
    profiles: ["ja"],
    regions: [
      {
        name: "Tokyo",
        cities: ["Tokyo"],
      },
      {
        name: "Kyoto",
        cities: ["Kyoto"],
      },
      {
        name: "Osaka",
        cities: ["Osaka"],
      },
      {
        name: "Hokkaido",
        cities: ["Sapporo", "Hakodate"],
      },
      {
        name: "Fukuoka",
        cities: ["Fukuoka", "Kitakyushu"],
      },
      {
        name: "Aichi",
        cities: ["Nagoya"],
      },
      {
        name: "Kanagawa",
        cities: ["Yokohama", "Kamakura"],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "KZ",
    name: "Kazakhstan",
    aliases: [],
    profiles: ["kz", "ru"],
    regions: [
      {
        name: "Astana",
        cities: ["Astana"],
      },
      {
        name: "Almaty",
        cities: ["Almaty"],
      },
      {
        name: "Shymkent",
        cities: ["Shymkent"],
      },
      {
        name: "Karaganda Region",
        cities: ["Karaganda", "Temirtau"],
      },
      {
        name: "Turkistan Region",
        cities: ["Turkistan", "Kentau"],
      },
      {
        name: "Atyrau Region",
        cities: ["Atyrau"],
      },
      {
        name: "East Kazakhstan Region",
        cities: ["Oskemen"],
      },
    ],
    continents: ["Europe", "Asia"],
  },
  {
    id: "KE",
    name: "Kenya",
    aliases: [],
    profiles: ["ke-sw"],
    regions: [
      {
        name: "Mombasa",
        cities: ["Mombasa"],
        profiles: ["ke-sw"],
      },
      {
        name: "Lamu",
        cities: ["Lamu"],
        profiles: ["ke-sw"],
      },
      {
        name: "Nairobi",
        cities: ["Nairobi"],
        profiles: [],
      },
      {
        name: "Kisumu",
        cities: ["Kisumu"],
        profiles: [],
      },
      {
        name: "Nakuru",
        cities: ["Nakuru"],
        profiles: [],
      },
    ],
    continents: ["Africa"],
  },
  {
    id: "MX",
    name: "Mexico",
    aliases: ["México"],
    profiles: ["mx"],
    regions: [
      {
        name: "Mexico City",
        cities: ["Mexico City"],
      },
      {
        name: "Jalisco",
        cities: ["Guadalajara", "Puerto Vallarta"],
      },
      {
        name: "Nuevo León",
        cities: ["Monterrey"],
      },
      {
        name: "Oaxaca",
        cities: ["Oaxaca de Juárez"],
      },
      {
        name: "Yucatán",
        cities: ["Mérida"],
      },
      {
        name: "Baja California",
        cities: ["Tijuana", "Ensenada"],
      },
      {
        name: "Puebla",
        cities: ["Puebla"],
      },
      {
        name: "Veracruz",
        cities: ["Veracruz", "Xalapa"],
      },
    ],
    continents: ["North America"],
  },
  {
    id: "MA",
    name: "Morocco",
    aliases: [],
    profiles: ["ma-ar"],
    regions: [
      {
        name: "Casablanca-Settat",
        cities: ["Casablanca", "Settat"],
      },
      {
        name: "Rabat-Salé-Kénitra",
        cities: ["Rabat", "Salé", "Kénitra"],
      },
      {
        name: "Marrakesh-Safi",
        cities: ["Marrakesh", "Safi"],
      },
      {
        name: "Fès-Meknès",
        cities: ["Fès", "Meknès"],
      },
      {
        name: "Tangier-Tetouan-Al Hoceima",
        cities: ["Tangier", "Tetouan"],
      },
      {
        name: "Souss-Massa",
        cities: ["Agadir", "Taroudant"],
        profiles: [],
      },
    ],
    continents: ["Africa"],
  },
  {
    id: "NZ",
    name: "New Zealand",
    aliases: ["Aotearoa"],
    profiles: ["nz-en"],
    regions: [
      {
        name: "Auckland",
        cities: ["Auckland", "Manukau"],
      },
      {
        name: "Wellington",
        cities: ["Wellington", "Lower Hutt"],
      },
      {
        name: "Canterbury",
        cities: ["Christchurch", "Timaru"],
      },
      {
        name: "Otago",
        cities: ["Dunedin", "Queenstown"],
      },
      {
        name: "Waikato",
        cities: ["Hamilton", "Taupō"],
      },
      {
        name: "Bay of Plenty",
        cities: ["Tauranga", "Rotorua"],
      },
    ],
    continents: ["Oceania"],
  },
  {
    id: "NG",
    name: "Nigeria",
    aliases: [],
    profiles: ["yo", "ng-ig", "ng-ha"],
    regions: [
      {
        name: "Lagos",
        cities: ["Lagos", "Ikeja"],
        profiles: ["yo", "ng-ig", "ng-ha"],
      },
      {
        name: "Oyo",
        cities: ["Ibadan"],
        profiles: ["yo"],
      },
      {
        name: "Ogun",
        cities: ["Abeokuta"],
        profiles: ["yo"],
      },
      {
        name: "Osun",
        cities: ["Ile-Ife", "Osogbo"],
        profiles: ["yo"],
      },
      {
        name: "Enugu",
        cities: ["Enugu"],
        profiles: ["ng-ig"],
      },
      {
        name: "Anambra",
        cities: ["Awka", "Onitsha"],
        profiles: ["ng-ig"],
      },
      {
        name: "Imo",
        cities: ["Owerri"],
        profiles: ["ng-ig"],
      },
      {
        name: "Kano",
        cities: ["Kano"],
        profiles: ["ng-ha"],
      },
      {
        name: "Kaduna",
        cities: ["Kaduna", "Zaria"],
        profiles: ["ng-ha"],
      },
      {
        name: "Federal Capital Territory",
        cities: ["Abuja"],
        profiles: ["yo", "ng-ig", "ng-ha"],
      },
      {
        name: "Rivers",
        cities: ["Port Harcourt"],
        profiles: [],
      },
    ],
    continents: ["Africa"],
  },
  {
    id: "PK",
    name: "Pakistan",
    aliases: [],
    profiles: ["pk-ur"],
    regions: [
      {
        name: "Sindh",
        cities: ["Karachi", "Hyderabad"],
        profiles: ["pk-ur"],
      },
      {
        name: "Punjab",
        cities: ["Lahore", "Faisalabad", "Rawalpindi"],
        profiles: ["pk-ur"],
      },
      {
        name: "Islamabad Capital Territory",
        cities: ["Islamabad"],
        profiles: ["pk-ur"],
      },
      {
        name: "Khyber Pakhtunkhwa",
        cities: ["Peshawar", "Abbottabad"],
        profiles: [],
      },
      {
        name: "Balochistan",
        cities: ["Quetta", "Gwadar"],
        profiles: [],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "PE",
    name: "Peru",
    aliases: [],
    profiles: ["pe-es"],
    regions: [
      {
        name: "Lima",
        cities: ["Lima", "Huacho"],
      },
      {
        name: "Arequipa",
        cities: ["Arequipa"],
      },
      {
        name: "Cusco",
        cities: ["Cusco"],
      },
      {
        name: "La Libertad",
        cities: ["Trujillo"],
      },
      {
        name: "Piura",
        cities: ["Piura", "Sullana"],
      },
      {
        name: "Loreto",
        cities: ["Iquitos"],
      },
    ],
    continents: ["South America"],
  },
  {
    id: "PH",
    name: "Philippines",
    aliases: [],
    profiles: ["ph"],
    regions: [
      {
        name: "Metro Manila",
        cities: ["Manila", "Quezon City"],
      },
      {
        name: "Central Visayas",
        cities: ["Cebu City"],
      },
      {
        name: "Davao Region",
        cities: ["Davao City"],
      },
      {
        name: "Western Visayas",
        cities: ["Iloilo City"],
      },
      {
        name: "Cordillera Administrative Region",
        cities: ["Baguio"],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "PL",
    name: "Poland",
    aliases: ["Polska"],
    profiles: ["pl"],
    regions: [
      {
        name: "Masovia",
        cities: ["Warsaw"],
      },
      {
        name: "Lesser Poland",
        cities: ["Kraków"],
      },
      {
        name: "Lower Silesia",
        cities: ["Wrocław"],
      },
      {
        name: "Pomerania",
        cities: ["Gdańsk"],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "PT",
    name: "Portugal",
    aliases: [],
    profiles: ["pt"],
    regions: [
      {
        name: "Lisbon District",
        cities: ["Lisbon", "Sintra"],
      },
      {
        name: "Porto District",
        cities: ["Porto", "Vila Nova de Gaia"],
      },
      {
        name: "Braga District",
        cities: ["Braga", "Guimarães"],
      },
      {
        name: "Faro District",
        cities: ["Faro", "Lagos"],
      },
      {
        name: "Coimbra District",
        cities: ["Coimbra"],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "RU",
    name: "Russia",
    aliases: ["Russian Federation"],
    profiles: ["ru", "ru-tt"],
    regions: [
      {
        name: "Moscow",
        cities: ["Moscow"],
        profiles: ["ru"],
      },
      {
        name: "Saint Petersburg",
        cities: ["Saint Petersburg"],
        profiles: ["ru"],
      },
      {
        name: "Novosibirsk Oblast",
        cities: ["Novosibirsk"],
        profiles: ["ru"],
      },
      {
        name: "Sverdlovsk Oblast",
        cities: ["Yekaterinburg"],
        profiles: ["ru"],
      },
      {
        name: "Krasnodar Krai",
        cities: ["Krasnodar", "Sochi"],
        profiles: ["ru"],
      },
      {
        name: "Primorsky Krai",
        cities: ["Vladivostok"],
        profiles: ["ru"],
      },
      {
        name: "Irkutsk Oblast",
        cities: ["Irkutsk"],
        profiles: ["ru"],
      },
      {
        name: "Tatarstan",
        cities: ["Kazan", "Naberezhnye Chelny", "Almetyevsk"],
        profiles: ["ru-tt", "ru"],
      },
      {
        name: "Sakha Republic",
        cities: ["Yakutsk"],
        profiles: [],
      },
      {
        name: "Moscow Oblast",
        cities: ["Khimki", "Kolomna", "Sergiyev Posad"],
        profiles: ["ru"],
      },
      {
        name: "Nizhny Novgorod Oblast",
        cities: ["Nizhny Novgorod", "Dzerzhinsk"],
        profiles: ["ru"],
      },
      {
        name: "Samara Oblast",
        cities: ["Samara", "Tolyatti"],
        profiles: ["ru"],
      },
      {
        name: "Rostov Oblast",
        cities: ["Rostov-on-Don", "Taganrog"],
        profiles: ["ru"],
      },
      {
        name: "Voronezh Oblast",
        cities: ["Voronezh", "Borisoglebsk"],
        profiles: ["ru"],
      },
      {
        name: "Volgograd Oblast",
        cities: ["Volgograd", "Volzhsky"],
        profiles: ["ru"],
      },
      {
        name: "Kaliningrad Oblast",
        cities: ["Kaliningrad", "Sovetsk"],
        profiles: ["ru"],
      },
      {
        name: "Arkhangelsk Oblast",
        cities: ["Arkhangelsk", "Severodvinsk"],
        profiles: ["ru"],
      },
      {
        name: "Murmansk Oblast",
        cities: ["Murmansk", "Apatity"],
        profiles: ["ru"],
      },
      {
        name: "Republic of Karelia",
        cities: ["Petrozavodsk", "Sortavala"],
        profiles: ["ru"],
      },
      {
        name: "Komi Republic",
        cities: ["Syktyvkar", "Ukhta"],
        profiles: [],
      },
      {
        name: "Perm Krai",
        cities: ["Perm", "Solikamsk"],
        profiles: ["ru"],
      },
      {
        name: "Chelyabinsk Oblast",
        cities: ["Chelyabinsk", "Magnitogorsk"],
        profiles: ["ru"],
      },
      {
        name: "Tyumen Oblast",
        cities: ["Tyumen", "Tobolsk"],
        profiles: ["ru"],
      },
      {
        name: "Omsk Oblast",
        cities: ["Omsk", "Tara"],
        profiles: ["ru"],
      },
      {
        name: "Tomsk Oblast",
        cities: ["Tomsk", "Seversk"],
        profiles: ["ru"],
      },
      {
        name: "Kemerovo Oblast",
        cities: ["Kemerovo", "Novokuznetsk"],
        profiles: ["ru"],
      },
      {
        name: "Krasnoyarsk Krai",
        cities: ["Krasnoyarsk", "Norilsk"],
        profiles: ["ru"],
      },
      {
        name: "Khabarovsk Krai",
        cities: ["Khabarovsk", "Komsomolsk-on-Amur"],
        profiles: ["ru"],
      },
      {
        name: "Kamchatka Krai",
        cities: ["Petropavlovsk-Kamchatsky", "Yelizovo"],
        profiles: ["ru"],
      },
      {
        name: "Sakhalin Oblast",
        cities: ["Yuzhno-Sakhalinsk", "Korsakov"],
        profiles: ["ru"],
      },
      {
        name: "Republic of Buryatia",
        cities: ["Ulan-Ude", "Severobaykalsk"],
        profiles: [],
      },
      {
        name: "Republic of Tuva",
        cities: ["Kyzyl"],
        profiles: [],
      },
      {
        name: "Altai Republic",
        cities: ["Gorno-Altaysk"],
        profiles: [],
      },
      {
        name: "Republic of Bashkortostan",
        cities: ["Ufa", "Sterlitamak"],
        profiles: [],
      },
      {
        name: "Republic of Dagestan",
        cities: ["Makhachkala", "Derbent"],
        profiles: [],
      },
      {
        name: "Chechen Republic",
        cities: ["Grozny", "Gudermes"],
        profiles: [],
      },
    ],
    continents: ["Europe", "Asia"],
  },
  {
    id: "WS",
    name: "Samoa",
    aliases: [],
    profiles: ["ws"],
    regions: [
      {
        name: "Tuamasaga",
        cities: ["Apia", "Afega"],
      },
      {
        name: "Aana",
        cities: ["Leulumoega"],
      },
      {
        name: "Fa’asaleleaga",
        cities: ["Salelologa"],
      },
    ],
    continents: ["Oceania"],
  },
  {
    id: "SA",
    name: "Saudi Arabia",
    aliases: [],
    profiles: ["sa-ar"],
    regions: [
      {
        name: "Riyadh",
        cities: ["Riyadh"],
      },
      {
        name: "Makkah",
        cities: ["Jeddah", "Mecca"],
      },
      {
        name: "Madinah",
        cities: ["Medina"],
      },
      {
        name: "Eastern Province",
        cities: ["Dammam", "Al Khobar"],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "ZA",
    name: "South Africa",
    aliases: [],
    profiles: ["za-zu", "za-xh", "za-af"],
    regions: [
      {
        name: "KwaZulu-Natal",
        cities: ["Durban", "Pietermaritzburg"],
        profiles: ["za-zu"],
      },
      {
        name: "Eastern Cape",
        cities: ["Mthatha", "Gqeberha"],
        profiles: ["za-xh"],
      },
      {
        name: "Western Cape",
        cities: ["Cape Town", "Stellenbosch"],
        profiles: ["za-af", "za-xh"],
      },
      {
        name: "Gauteng",
        cities: ["Johannesburg", "Pretoria"],
        profiles: ["za-zu", "za-af"],
      },
      {
        name: "Free State",
        cities: ["Bloemfontein"],
        profiles: [],
      },
      {
        name: "Limpopo",
        cities: ["Polokwane"],
        profiles: [],
      },
    ],
    continents: ["Africa"],
  },
  {
    id: "KR",
    name: "South Korea",
    aliases: ["Republic of Korea"],
    profiles: ["ko"],
    regions: [
      {
        name: "Seoul",
        cities: ["Seoul"],
      },
      {
        name: "Busan",
        cities: ["Busan"],
      },
      {
        name: "Incheon",
        cities: ["Incheon"],
      },
      {
        name: "Gyeonggi",
        cities: ["Suwon", "Seongnam"],
      },
      {
        name: "Jeju",
        cities: ["Jeju City", "Seogwipo"],
      },
    ],
    continents: ["Asia"],
  },
  {
    id: "ES",
    name: "Spain",
    aliases: ["España"],
    profiles: ["es", "es-ca"],
    regions: [
      {
        name: "Community of Madrid",
        cities: ["Madrid"],
        profiles: ["es"],
      },
      {
        name: "Catalonia",
        cities: ["Barcelona", "Girona"],
        profiles: ["es-ca", "es"],
      },
      {
        name: "Andalusia",
        cities: ["Seville", "Málaga", "Granada"],
        profiles: ["es"],
      },
      {
        name: "Valencian Community",
        cities: ["Valencia", "Alicante"],
        profiles: ["es", "es-ca"],
      },
      {
        name: "Galicia",
        cities: ["A Coruña", "Vigo"],
        profiles: [],
      },
      {
        name: "Basque Country",
        cities: ["Bilbao", "San Sebastián"],
        profiles: [],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "SE",
    name: "Sweden",
    aliases: [],
    profiles: ["sv"],
    regions: [
      {
        name: "Stockholm County",
        cities: ["Stockholm", "Södertälje"],
      },
      {
        name: "Västra Götaland County",
        cities: ["Gothenburg", "Borås"],
      },
      {
        name: "Skåne County",
        cities: ["Malmö", "Lund"],
      },
      {
        name: "Uppsala County",
        cities: ["Uppsala"],
      },
      {
        name: "Västerbotten County",
        cities: ["Umeå"],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "TZ",
    name: "Tanzania",
    aliases: [],
    profiles: ["tz-sw"],
    regions: [
      {
        name: "Dar es Salaam",
        cities: ["Dar es Salaam"],
      },
      {
        name: "Dodoma",
        cities: ["Dodoma"],
      },
      {
        name: "Arusha",
        cities: ["Arusha"],
      },
      {
        name: "Zanzibar Urban/West",
        cities: ["Zanzibar City"],
      },
      {
        name: "Mwanza",
        cities: ["Mwanza"],
        profiles: [],
      },
    ],
    continents: ["Africa"],
  },
  {
    id: "TO",
    name: "Tonga",
    aliases: [],
    profiles: ["to"],
    regions: [
      {
        name: "Tongatapu",
        cities: ["Nukuʻalofa", "Muʻa"],
      },
      {
        name: "Vavaʻu",
        cities: ["Neiafu"],
      },
      {
        name: "Haʻapai",
        cities: ["Pangai"],
      },
    ],
    continents: ["Oceania"],
  },
  {
    id: "TR",
    name: "Türkiye",
    aliases: ["Turkey"],
    profiles: ["tr"],
    regions: [
      {
        name: "Istanbul",
        cities: ["Istanbul"],
      },
      {
        name: "Ankara",
        cities: ["Ankara"],
      },
      {
        name: "Izmir",
        cities: ["Izmir"],
      },
      {
        name: "Antalya",
        cities: ["Antalya"],
      },
      {
        name: "Bursa",
        cities: ["Bursa"],
      },
      {
        name: "Diyarbakır",
        cities: ["Diyarbakır"],
        profiles: [],
      },
    ],
    continents: ["Europe", "Asia"],
  },
  {
    id: "UA",
    name: "Ukraine",
    aliases: [],
    profiles: ["ua"],
    regions: [
      {
        name: "Kyiv",
        cities: ["Kyiv"],
      },
      {
        name: "Lviv Oblast",
        cities: ["Lviv"],
      },
      {
        name: "Odesa Oblast",
        cities: ["Odesa"],
      },
      {
        name: "Kharkiv Oblast",
        cities: ["Kharkiv"],
      },
      {
        name: "Dnipropetrovsk Oblast",
        cities: ["Dnipro"],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "GB",
    name: "United Kingdom",
    aliases: ["UK", "Britain", "Great Britain"],
    profiles: ["en"],
    regions: [
      {
        name: "England",
        cities: ["London", "Bristol", "Manchester", "Birmingham", "Liverpool"],
      },
      {
        name: "Scotland",
        cities: ["Edinburgh", "Glasgow", "Aberdeen"],
      },
      {
        name: "Wales",
        cities: ["Cardiff", "Swansea"],
      },
      {
        name: "Northern Ireland",
        cities: ["Belfast", "Derry"],
      },
    ],
    continents: ["Europe"],
  },
  {
    id: "US",
    name: "United States",
    aliases: ["USA", "U.S.A.", "United States of America"],
    profiles: ["us-en", "us-es"],
    regions: [
      {
        name: "Alabama",
        cities: ["Birmingham", "Montgomery", "Huntsville", "Mobile"],
      },
      {
        name: "Alaska",
        cities: ["Anchorage", "Fairbanks", "Juneau"],
      },
      {
        name: "Arizona",
        cities: ["Phoenix", "Tucson", "Mesa", "Flagstaff"],
      },
      {
        name: "Arkansas",
        cities: ["Little Rock", "Fayetteville", "Fort Smith"],
      },
      {
        name: "California",
        cities: [
          "Los Angeles",
          "San Francisco",
          "San Diego",
          "Sacramento",
          "San Jose",
          "Oakland",
          "Fresno",
          "Long Beach",
        ],
        profiles: ["us-en", "us-es"],
      },
      {
        name: "Colorado",
        cities: ["Denver", "Colorado Springs", "Boulder", "Fort Collins"],
      },
      {
        name: "Connecticut",
        cities: ["Hartford", "New Haven", "Bridgeport"],
      },
      {
        name: "Delaware",
        cities: ["Wilmington", "Dover", "Newark"],
      },
      {
        name: "District of Columbia",
        cities: ["Washington"],
      },
      {
        name: "Florida",
        cities: [
          "Miami",
          "Orlando",
          "Tampa",
          "Jacksonville",
          "Tallahassee",
          "St. Petersburg",
          "Fort Lauderdale",
        ],
        profiles: ["us-en", "us-es"],
      },
      {
        name: "Georgia",
        cities: ["Atlanta", "Savannah", "Augusta", "Athens"],
      },
      {
        name: "Hawaii",
        cities: ["Honolulu", "Hilo", "Kailua-Kona"],
        profiles: [],
      },
      {
        name: "Idaho",
        cities: ["Boise", "Idaho Falls", "Coeur d’Alene"],
      },
      {
        name: "Illinois",
        cities: ["Chicago", "Springfield", "Aurora", "Peoria"],
      },
      {
        name: "Indiana",
        cities: ["Indianapolis", "Fort Wayne", "Bloomington"],
      },
      {
        name: "Iowa",
        cities: ["Des Moines", "Cedar Rapids", "Iowa City"],
      },
      {
        name: "Kansas",
        cities: ["Wichita", "Topeka", "Lawrence"],
      },
      {
        name: "Kentucky",
        cities: ["Louisville", "Lexington", "Bowling Green"],
      },
      {
        name: "Louisiana",
        cities: ["New Orleans", "Baton Rouge", "Lafayette", "Shreveport"],
      },
      {
        name: "Maine",
        cities: ["Portland", "Augusta", "Bangor"],
      },
      {
        name: "Maryland",
        cities: ["Baltimore", "Annapolis", "Frederick"],
      },
      {
        name: "Massachusetts",
        cities: ["Boston", "Worcester", "Cambridge", "Springfield"],
      },
      {
        name: "Michigan",
        cities: ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing"],
      },
      {
        name: "Minnesota",
        cities: ["Minneapolis", "Saint Paul", "Duluth"],
      },
      {
        name: "Mississippi",
        cities: ["Jackson", "Gulfport", "Hattiesburg"],
      },
      {
        name: "Missouri",
        cities: ["Kansas City", "St. Louis", "Columbia"],
      },
      {
        name: "Montana",
        cities: ["Billings", "Missoula", "Bozeman"],
      },
      {
        name: "Nebraska",
        cities: ["Omaha", "Lincoln", "Bellevue"],
      },
      {
        name: "Nevada",
        cities: ["Las Vegas", "Reno", "Carson City"],
      },
      {
        name: "New Hampshire",
        cities: ["Manchester", "Concord", "Portsmouth"],
      },
      {
        name: "New Jersey",
        cities: ["Newark", "Jersey City", "Trenton", "Princeton"],
      },
      {
        name: "New Mexico",
        cities: ["Albuquerque", "Santa Fe", "Las Cruces"],
        profiles: ["us-en", "us-es"],
      },
      {
        name: "New York",
        cities: [
          "New York City",
          "Buffalo",
          "Albany",
          "Rochester",
          "Syracuse",
          "Yonkers",
        ],
        profiles: ["us-en", "us-es"],
      },
      {
        name: "North Carolina",
        cities: ["Charlotte", "Raleigh", "Durham", "Asheville"],
      },
      {
        name: "North Dakota",
        cities: ["Fargo", "Bismarck", "Grand Forks"],
      },
      {
        name: "Ohio",
        cities: ["Columbus", "Cleveland", "Cincinnati", "Dayton", "Toledo"],
      },
      {
        name: "Oklahoma",
        cities: ["Oklahoma City", "Tulsa", "Norman"],
      },
      {
        name: "Oregon",
        cities: ["Portland", "Eugene", "Salem", "Bend"],
      },
      {
        name: "Pennsylvania",
        cities: ["Philadelphia", "Pittsburgh", "Harrisburg", "Allentown"],
      },
      {
        name: "Rhode Island",
        cities: ["Providence", "Newport", "Warwick"],
      },
      {
        name: "South Carolina",
        cities: ["Charleston", "Columbia", "Greenville"],
      },
      {
        name: "South Dakota",
        cities: ["Sioux Falls", "Rapid City", "Pierre"],
      },
      {
        name: "Tennessee",
        cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga"],
      },
      {
        name: "Texas",
        cities: [
          "Houston",
          "Austin",
          "Dallas",
          "San Antonio",
          "Fort Worth",
          "El Paso",
          "Lubbock",
        ],
        profiles: ["us-en", "us-es"],
      },
      {
        name: "Utah",
        cities: ["Salt Lake City", "Provo", "Ogden"],
      },
      {
        name: "Vermont",
        cities: ["Burlington", "Montpelier", "Rutland"],
      },
      {
        name: "Virginia",
        cities: [
          "Virginia Beach",
          "Richmond",
          "Norfolk",
          "Charlottesville",
          "Alexandria",
          "Roanoke",
          "Newport News",
        ],
        profiles: ["us-en"],
      },
      {
        name: "Washington",
        cities: ["Seattle", "Spokane", "Tacoma", "Olympia"],
      },
      {
        name: "West Virginia",
        cities: ["Charleston", "Morgantown", "Huntington"],
      },
      {
        name: "Wisconsin",
        cities: ["Milwaukee", "Madison", "Green Bay"],
      },
      {
        name: "Wyoming",
        cities: ["Cheyenne", "Casper", "Laramie"],
      },
    ],
    continents: ["North America"],
  },
  {
    id: "VN",
    name: "Vietnam",
    aliases: ["Viet Nam"],
    profiles: ["vn"],
    regions: [
      {
        name: "Hanoi",
        cities: ["Hanoi"],
      },
      {
        name: "Ho Chi Minh City",
        cities: ["Ho Chi Minh City"],
      },
      {
        name: "Da Nang",
        cities: ["Da Nang"],
      },
      {
        name: "Hue",
        cities: ["Hue"],
      },
      {
        name: "Can Tho",
        cities: ["Can Tho"],
      },
    ],
    continents: ["Asia"],
  },
];
