import {chromium} from '@playwright/test';
import {writeFileSync,mkdirSync} from 'node:fs';
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3000';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text())});
mkdirSync('artifacts/screenshots',{recursive:true});
await page.goto(base);await page.getByRole('button',{name:'Open The Quiet Protocol',exact:true}).waitFor();
await page.screenshot({path:'artifacts/screenshots/library-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Open The Quiet Protocol',exact:true}).click();await page.getByLabel('Chapter manuscript').waitFor();
await page.screenshot({path:'artifacts/screenshots/manuscript-desktop.png',fullPage:true});
await page.goto(base+'/#/series');await page.locator('.series-card').filter({hasText:'The Unwritten System'}).getByRole('button',{name:'Open series planner',exact:true}).click();
await page.getByRole('heading',{name:'The Unwritten System',exact:true}).waitFor();await page.screenshot({path:'artifacts/screenshots/series-desktop.png',fullPage:true});
await page.goto(base+'/#/forge');await page.getByRole('heading',{name:'The story forge',exact:true}).waitFor();await page.screenshot({path:'artifacts/screenshots/forge-desktop.png',fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1,reducedMotion:'reduce'});
await mobile.goto(base);await mobile.getByRole('button',{name:'Open The Quiet Protocol',exact:true}).waitFor();
await mobile.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=0);
await mobile.screenshot({path:'artifacts/screenshots/library-mobile.png',fullPage:true});
const mobileOverflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
await mobile.getByRole('button',{name:'Open The Quiet Protocol',exact:true}).click();await mobile.getByLabel('Chapter manuscript').waitFor();
await mobile.screenshot({path:'artifacts/screenshots/manuscript-mobile.png',fullPage:true});
writeFileSync('artifacts/visual-smoke.json',JSON.stringify({desktopViewport:{width:1440,height:1000},mobileViewport:{width:390,height:844},mobileHorizontalOverflow:mobileOverflow,desktopErrors:errors,note:'Synthetic preview; screenshots are not live-model evidence.'},null,2));
await browser.close();if(errors.length||mobileOverflow)process.exitCode=1;
